# Generated by Django 4.1.7 on 2023-04-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdb',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
