# Generated by Django 4.1.7 on 2023-04-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contactdb_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='singupdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=60, null=True)),
                ('re_password', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
