# Generated by Django 4.1.7 on 2023-05-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='productname',
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
