# Generated by Django 4.1.7 on 2023-05-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='date_added',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
