# Generated by Django 4.1.7 on 2023-05-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_cartmodel_date_added_cartmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='image',
        ),
    ]
