# Generated by Django 4.1.7 on 2023-05-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_cartmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='user',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
