# Generated by Django 4.1.7 on 2023-05-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_buycart'),
    ]

    operations = [
        migrations.CreateModel(
            name='carbuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productnm', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('price', models.IntegerField(blank=True, null=True, unique=True)),
                ('quantity', models.PositiveIntegerField(null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='buycart',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
