# Generated by Django 4.1.7 on 2023-05-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_carbuy_alter_buycart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carbuy',
        ),
        migrations.AddField(
            model_name='buycart',
            name='user',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
