# Generated by Django 4.1.7 on 2023-05-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_buycart_address_buycart_city_buycart_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admincart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productnm', models.CharField(blank=True, max_length=60, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('user', models.CharField(blank=True, max_length=60, null=True)),
                ('firstname', models.CharField(blank=True, max_length=60, null=True)),
                ('lastname', models.CharField(blank=True, max_length=60, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
